### ISSUE TITLE
build_process_tree struck in while loop

### ISSUE THREAD

**Issue by weichea** [microsoft/msticpy#148]
**Describe the bug**
I tried to run the build_process_tree on mordor data. It seems to went into a loop.  I did some check and seems like "max_depth" in _build_proc_tree() is always -1? 

**To Reproduce**
```
df2 = mdr_data.small.windows.credential_access.host.empire_shell_rubeus_asktgt_createnetonly()
df2.rename(columns={'Hostname': 'Computer', 'ActivityID': 'TenantId'}, inplace=True)
df_new = df2[['TenantId', 'Computer', 'EventID', '@timestamp', 'NewProcessName', 'NewProcessId', 'ParentProcessName', 'ProcessId', 'SubjectLogonId', 'TargetLogonId', 'CommandLine', 'SubjectUserName', 'SubjectUserSid']].drop_duplicates()
df_new['@timestamp'] = pd.to_datetime(df_new['@timestamp'])
p_tree_win = ptree.build_process_tree(df_new, schema=schema, show_progress=True)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/13419219/112727013-507b8400-8f5b-11eb-9cba-2b3961dc0b20.png)

**Comment by ianhelle** [comment]
@weichea - thanks for the bug report.
The Mordor data is mostly sysmon (rather than Win Evt log) so not sure that it has the right schema to work with this. Can you tell me which data set you are using? Since Sysmon (unlike Win event log and Linux audit) keeps more detailed (and less ambiguous) process tree info, it may not need the bulk of the logic we use on these other event types.
I suspect that the parent_key field is not being calculated in a way that makes sense for the sysmon data so you get duplicates and, at some point, a cycle.
I've made a change so that, on each loop, it removes the selected "current_level" procs from those remaining and then operates only on the remaining_procs on the next loop (previously it selected the current level from the entire dataframe - so if you had data that suggested a parent child tree something like this A->B->C->A, it would never exit. In the new code "A" would get removed on the first pass so could never be selected as a child of C.
Commit is here: https://github.com/microsoft/msticpy/commit/229ee0948ae4370de78dd6321de40a4884d700e7

Happy to test the Mordor data if you can tell me which data set you're using (although if I have to make bigger changes to the proc tree logic to work with Sysmon it might take a bit longer to work out.

I can also prob switch the defaults to something like max_depth = 10 and then surface this parameter higher up. But this a bit of a crude control.

**Comment by weichea** [comment]
@ianhelle Thank you for looking into this!

I have tried your fix, the loop issue is resolved. The plotting doesn't seem to be plotting correctly, not sure if that's because of my jupyter notebook setup. I need to take a further look. 

I'm using the _small.windows.credential_access.host.empire_shell_rubeus_asktgt_createnetonly_ dataset. The data do contain 4688 events, but I had to rename the **Hostname** column -> **Computer** and added a **TenantId** column to get it to work.

**Comment by ianhelle** [comment]
@weichea NP. Always happy to fix things.
Could be that I am taking too many dependencies on the Azure Sentinel Schema - (e.g. the auto-population of the Computer column) - I'll take a look at this.
If you want to try with data known to work have a go with this https://github.com/microsoft/msticpy/blob/master/docs/notebooks/data/win_proc_test.pkl
That will distinguish data from display problems. Bokeh can be a bit picky sometimes. You poss need the Jupyterlab extension if you are using in Jupyter lab.
I will try to look at the Mordor data set since it would be good to get this working.

**Comment by ianhelle** [comment]
This should now be in the released version. Thx for reporting. I've opened a new issue #151 to track some other improvements that I'd like to make to this.
