### ISSUE TITLE
[FeatureRequest] Cross query multiple instances

### ISSUE THREAD

**Issue by juju4** [microsoft/msticpy#210]
**Is your feature request related to a problem? Please describe.**
For most companies, there are likely multiple instances of logs due to data residency or other architecture constraint.
Analyst may want to execute queries and playbook on those multiple instances in one play instead of one by one, to have a global view, to quicken analysis or else.

**Describe the solution you'd like**

1. Each data provider should support configuration of multiple instances - currently only Sentinel.
2. Each data provider should allow async query so multiple queries can be executed in background. believe missing for kqlmagic
3. Add in msticpy to allow one query to execute on an instances set. this likely should add an instance column to allow differentiation.

**Describe alternatives you've considered**

The normal current alternative is to execute playbook once per instance or loop by instances with manual data merging.

**Comment by ianhelle** [comment]
This seems like an interesting idea.
One thought I had to is give a query provider a method to add_connection() - so that you could add multiple connections (to different workspaces/data providers).
Any queries run from this provider would execute across all connections and combine the results before returning.

A couple of possible implementations:
- Create QueryProvider - allow add_connection() method as alternative to connect() (or after connect() has been called once). add_connection would run through the authentication flow for that connection.
- add_connection takes an existing query provider as a parameter (this seems a bit klunky) 
- maybe have add_all_connections() to add all configured providers
For config syntax (in msticpyconfig.yaml)
Easiest/least disruptive way would seem to be to have an optional "instance-name" value.
This would be saved in the config file as the provider title - SumoLogic-instance1
Keeping the structure the same as will make it easier to integrate into the current config UI editor.

Questions: 
1. once a QueryProvider has multiple connections, should it be possible to run queries for just one connection (or a subset of connections)? Or is it OK to have this provider always run for all connections. We could introduce another parameter to the query run - something like connections={name | [name1, name2]} - that instructed the query to run only on the named subset
2. How to handle disparate resutls/errors for multiple connections.
    - data/connection errors - no data/partial data - we could add a null dataframe and report the error
    - schema errors - no table, schema/query error - probably as above but would need to give a way for user to obtain more detailed debug info
    - different but compatible schema - e.g. connections 1 and 2 both run successfully but return different schemas - I think we'd have to just merge into a single dataframe
3. Do we need to encode the connection name in the results - e.g. as another column?
