### ISSUE TITLE
HTTPX default parameters behaves differently than requests default parameters

### ISSUE THREAD

**Issue by FlorianBracq** [microsoft/msticpy#334]
**Is your feature request related to a problem?**
Wehn switching from request to httpx, different default behaviors were changes:
* Follow redirect:
  * in requests: enabled by default
  * in httpx: disabled by default (https://www.python-httpx.org/compatibility/#redirects)
  >Unlike requests, HTTPX does not follow redirects by default.
* Timeout:
  *  Requests: No timeouts defined (https://docs.python-requests.org/en/master/user/advanced/#timeouts)
  > By default, requests do not time out unless a timeout value is set explicitly.
  * Httpx: Tiemouts to 5s (https://www.python-httpx.org/advanced/#timeout-configuration)
  > The default behavior is to raise a TimeoutException after 5 seconds of network inactivity.

**Describe the solution you'd like**
Define HTTPX Client with a 30s timeout and to follow redirect (required at least for the Cybereason driver)

**Additional context**
Some TI lookupts could hit the 5s timeout limit if multiple IOCs are queried.

Suggested solution:
_msticpy\sectools\tiproviders\http_base.py_
from
```
self._httpx_client = httpx.Client()
```
to
```
self._httpx_client = httpx.Client(timeout=30.0, follow_redirects=True)
```

**Comment by ianhelle** [comment]
Hey Florian, thanks for pointing this out. One thing to note is that the change to the redirect default is probably because it's seen as a better security default. Not sure why the timeout is different.

We have a couple of options here:
1. change http_base defaults (as you suggested)
2. change http_base so it takes args from the child class to specify timeout and redirect behavior - so each TI provider would have to opt in.
3. change the defaults everywhere.

In the case of 1 and 3 we could also make this configurable - so that a user could turn off/on redirects and change the timeout.
Any thoughts?

**Comment by FlorianBracq** [comment]
Hi Ian,

you are right, option 2 sounds like a better option!
I agree that redirect can be considered as a good security default and should thus default to False, but what about timeout?

I've hit  this 5s timeout quite often while doing TI lookups. I don't know if it means my network is bad or if 5s is too low for the default value?

**Comment by ianhelle** [comment]
I don't see any downside in making 30 sec default timeout.
We'll try to get both of these in a 1.7.1 this or next week.
