### ISSUE TITLE
Remind user to Update and Validate Settings when editing msticpyconfig.yaml with MpConfigEdit()

### ISSUE THREAD

**Issue by titanicshark** [microsoft/msticpy#391]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be useful if msticpy reminded users via text output to Update and Validate Settings before Saving Changes when editing their msticpyconfig.yaml with MpConfigEdit().

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ianhelle** [comment]
It's difficult to detect when people have moved away from the setup widget - since it's not modal. It would be nice to have a visual reminder of unsaved changes.
Similarly, when users make a change to an item we could:
1. Warn before letting them navigate to something else, that there are changes that need updating
2. Have a visual indicator that the edited item is in a draft state
One way of doing that would be to disable the "Update" button until there are changes to update.

**Comment by ianhelle** [comment]
Have done this in documentation plus added check for unsaved data in config editor
