### ISSUE TITLE
Multi-instance/workspace/tenant usage documentation not working

### ISSUE THREAD

**Issue by juju4** [microsoft/msticpy#461]
**Describe the bug**

I saw https://github.com/microsoft/msticpy/commit/cf0a9a4bad6b9f1b00866ad688739439bfbc1c72 which seems great
but was not able to figure matching msticpyconfig.yaml syntax. An example in documentation would be nice

Note that MpConfigEdit does not allow for instance. Tested with Sumologic and if try to add another, it says that one already exists.

Sadly, I got into similar pitfalls for various providers as I must handle multi-tenancy, multi-workspaces
  * Sentinel side
It seems to always pick default workspace from msticpyconfig.yaml  whatever the connect parameters in ` ws_config = WorkspaceConfig(workspace=target_workspace) `
  * Sumologic side
Did not found instance syntax
Trying a custom file with ` os.environ['MSTICPYCONFIG'] = target_msticpyconfig ` is not applied. Only default msticpyconfig.yaml (not msticpyconfig-xxxx.yaml)

I tried to mirror Kusto explorer behavior without success
https://msticpy.readthedocs.io/en/latest/data_acquisition/DataProv-Kusto.html
If this reference is valid for all provider (likely with sentinel exception), likely want to "up" it as its own section in the documentation

**Comment by ianhelle** [comment]
The kusto provider works a little differently to other providers. There are some similarities to the multi-instance providers.

## Sentinel provider
Sentinel has, for historical reasons its own special space in msticpyconfig - before we thought of adding multiple providers.
Each entry under Workspaces should be a unique string ("Default" can be one of these). Then underneath each key are the workspace config params (TenantId, etc.). The key is usually the same as the workspace name but doesn't have to be.

The WorkspaceConfig(workspace="MyWorkspace") - "MyWorkspace" should match a key in this section of the config. It should (and does for me) correctly return the right workspace. It's job is just to build a connection string for the Kql package we use to connect. If you find that this isn't working please let me know.

## Other DataProviders
Only Sumologic supports multiple instances. I implemented in a bit of a hokey way since I'd already written the MpConfigEdit UI and it would have been hugely disruptive to this code to do it differently (a better way would have been something like Sentinel/Workspaces/ws1, etc.
The fudge I settled on for instances of a Data provider was:
- Under the DataProviders section there is a collection of DP entries with unique keys
- To create an instance-aware entry, the key for the entry should be DataProvider-InstanceKey (e.g. Sumologic-Workspace1)
- To use that entry you should connect the query provider with the instance="Workspace1"
- You can have any number of these as long as the DataProvider-InstanceKey is unique in the DataProviders section

Obviously this isn't explained very well in the docs.
It could also be that what I've just described isn't working correctly.

We should be able to fix both of these issues.

**Comment by ianhelle** [comment]
@juju4 - is this still valid. I thought I'd updated the UI (a while back) to support instances.
Will close for now LMK if this still isn't working
