### ISSUE TITLE
Data viewer is not working in notebook dark theame 

### ISSUE THREAD

**Issue by 4R9UN** [microsoft/msticpy#468]
Hi Team, 

I am very impressed and love to use the new update of the MSTICPY module, it's very helpful, Recently I have to use the data viewer function, and I have a dark theme by default in my notebook environment, the data viewer is not working properly in dark theme. we need to add some color functionality according to the notebook themes.

**Comment by ianhelle** [comment]
Not sure how easy it is for code in the notebook to be aware of the theme set - I imagine that there is some way you can check the CSS that you are inheriting but that all sounds very scary to me. We'll investigate this though.

A couple of other things:
1. We've been thinking about how we "theme" the graphics and widgets - so that we can at least control the theme from a msticpy setting. Bokeh plots support themes, not sure about ipywidgets.
2. The Dataview has a few issues:
    - The Bokeh `push_notebook` function doesn't seem to work in all environments - e.g. VSCode. This lets you push changes in Python to the JS Bokeh model (so updates the Data view display in this case). This means that changes you make to the filters or columns, don't get reflected in the data displayed.
    - The display of the data is a bit weak anyway. I opted to make the data cells editable so that you could more easily copy text from a cell. This has the side effect of making the text a medium grey color and more difficult to read.

I haven't done much to this control because of frustration about both these issues and thinking that, because of these, not many people would be using the feature. We could try to revisit this though.

**Comment by ianhelle** [comment]
Just adding a couple of relevant links for future reference:
VSCode/ipwidgets theme - https://github.com/microsoft/vscode-jupyter/issues/9403
https://docs.bokeh.org/en/latest/docs/reference/themes.html

**Comment by ianhelle** [comment]
We're probably going to implement a global theme switch for Bokeh plots. There isn't any easy way of telling (from code in a notebook) what theme the app (Jupyter lab, VSCode) is running - so this will have to be a separate msticpyconfig.yaml setting.

**Comment by 4R9UN** [comment]
that makes sense, else I would like to enable ag-grid/qgrid python module in MSTICPY, however, it has JS dependency that might be difficult, just a thought. I am also looking for alternative solutions for the issue .
