### ISSUE TITLE
Add extra information to queries

### ISSUE THREAD

**Issue by FlorianBracq** [microsoft/msticpy#475]
**Is your feature request related to a problem? Please describe.**
Msticpy queries can be used to retrieve data, but also through the print mechanism, can also be leveraged in a documentation framework to explain why is a query being executed, how to analyze its output and many other things. One of those key points that is missing today is the prerequisites for that request to be executable, namely:
* table
* fields required to query
* fields required for the output

**Describe the solution you'd like**
It would help to have defined within the YAML file hosting the queries the key fields/info for this query to easily highlight: if we want to run query X, you need A, B, C

**Comment by ianhelle** [comment]
We do already have the concept of required and optional parameters. The latter have a default value so are not required wheras the former always are.
This is is shown in the query help with the presence/absence of an (optional) tag on the parameters.
Also if you try to run or "print" a query without one or more required parameters you will get an error saying which parameters are missing.

One thing we don't do consistently is have "table" as a parameter. Having this as a parameter is usually moot - since the query probably won't work if you put in some other value than the default. It is useful to be easily able to extract this info though.

Some things we could do:

- Ensure that table is a parameter in all queries
- Add additional description or metadata elements that are displayed in the query help/query browser
- Have more sophisticated filtering in the query browser - e.g. to filter by table, parameter type, description substring, etc.
  (we are going to need something like this for an upcoming Sentinel feature that imports Hunting and Detection queries).
- Have a command line query search that lets you do the same kind of filtering (we have something like this for the Mordor browser)

@Petebryan also suggested being able to browse/filter/search on queries from multiple providers. I think this is a cool idea - e.g. show me all queries that take ip_address as a parameter.

**Comment by FlorianBracq** [comment]
Adding a comment related to our past dicussions, while there would be limited values for queries, that would be more relevant to "pipelines"

**Comment by ianhelle** [comment]
I think I've added some support for this (although not all queries have a "table" attribute still.
There is query search support as of #587
It's always been a feature to show the underlying query in the function help.
LMK if this doesn't address all the concerns
