### ISSUE TITLE
IPython.notebook.kernel.execute errors from QueryProvider

### ISSUE THREAD

**Issue by jllangley** [microsoft/msticpy#522]
**Describe the bug**
Currently running the msticpy 2.1.2.
Verified this does not happen with msticpy 2.0

When the QueryProvider module is connecting to the LogAnalytics workspace to run a query I am getting this error 16 times.
'''
env: KQLMAGIC_LOAD_MODE=silent
'Finished the imports'

**try {IPython.notebook.kernel.execute("NOTEBOOK_URL = '" + window.location + "'");} catch(err) {;}**

'''

**To Reproduce**
### Running this from Azure ML studio
```
# %load _rundmz_.py
# Imports
from msticpy.common.utility import check_py_version

MIN_REQ_PYTHON = (3, 6)
check_py_version(MIN_REQ_PYTHON)

from typing import List, Dict, Union

# setting pandas display options for dataframe
import pandas as pd
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", 100)

%env KQLMAGIC_LOAD_MODE=silent

display('Finished the imports')

from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env.

from msticpy.data import QueryProvider
qry_prov = QueryProvider("LogAnalytics")
from msticpy.common.wsconfig import WorkspaceConfig
qry_prov.connect(WorkspaceConfig(workspace="redacted"), mp_az_auth="env")
```

**Expected behavior**
The try IPython catch error should not show up.

**Comment by ianhelle** [comment]
Hey folks, apologies for not responding to this earlier.
This is a bug in the Azure Notebooks renderer used in Azure Machine Learning and Azure Synapse. It is caused by the Kqlmagic library that we use trying to execute some javascript. Even though we don't need the functionality that Kqlmagic is trying to enable (adding a help menu), it is still a legitimate thing to do.
Azure notebooks is, for some reason, rendering this as plain text in a notebook output cell. They are currently investigating why this is happening and working on a fix.

It seems to happen when a cell has mixed output (e.g. plain text and html/JS). The best that we can do is to try to avoid situations where we mix outputs in cells but this is likely too much work to fix this in both MSTICPy and notebooks.

We will update this issue with progress.

**Comment by ianhelle** [comment]
Azure machine learning has rolled out a new version to address this regression.

**Comment by tuxnam** [comment]
Hello @ianhelle, not sure why but it does not seems to be fixed in jupyter notebooks in Sentinel using AML .Same error still simply when connecting to a QueryProvider using MSTICpy.

**Comment by kenshukubo** [comment]
@ianhelle 
Hi, this bug fixed?
