### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by sidraaleem-eaton** [microsoft/msticpy#531]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by petebryan** [comment]
Hi @sidraaleem-eaton I am having trouble replicating this issue.
Can you please provide details of what environment you are running this code in?

**Comment by ianhelle** [comment]
The only thing I can think can be causing this is fetching the Bokeh JS libraries. There should be no network/https access happening otherwise during import.
I think if you are behind a corporate firewall/proxy this could be the cause - the firewall is proxying the TLS traffic and returning its (self-signed) cert to Python. Since Python doesn't have this cert in its root store the https connection is failing.
Here's a discussion I found and links to ways to fix it by importing the cert into your Python cert store.
https://github.com/os/slacker/issues/148#issuecomment-645117805

**Comment by gkennos** [comment]
There is definitely network access during import (working in a restricted environment myself at the moment). Not sure if this is the same root cause of the above, as my error is not certificate-related, rather a total connection error, but also happening at import time.  It is caused by this line in context/ip_utils.py that is triggered on import. 

`
_ASNS = httpx.get("https://bgp.potaroo.net/cidr/autnums.html")`

**Comment by ianhelle** [comment]
We should fix that import-time network fetch.
I've submitted a PR for that.
