### ISSUE TITLE
How to create custom geoip lookup class? 

### ISSUE THREAD

**Issue by mathurin68** [microsoft/msticpy#561]
We have a couple of geoIP lookup services that we already use so I'm looking to 'Creating a Custom GeopIP Lookup Class' to use them.  

The part of the GeoIPLookups.ipynb notebook that displays "Creating a Custom GeoIP Lookup Class", I'm OK with python but I'm not sure how to use this.  

Can someone offer a hint about it?   I could have sworn I saw an article on techcommunity or somewhere on creating custom lookups with msticpy but I can't seem to find it anywhere. 

Thank you! 

P.S. great way to spend a Saturday playing with msticpy!!

**Comment by ianhelle** [comment]
Hi @mathurin68,

So creating a compatible GeoIP provider isn't too hard but there is a potential issue that it would be good to solve.
in msticpy.context.geoip there is a GeoIpLookup class. I always intended that other geoip providers could be derived from the class.
Doing that, and following the IpStackLookup class model in that file isn't too difficult. I've put some code that gives you an idea of what's needed. You only really need to implement the lookup_ip method. The base class handles lookup_ips by iterating through an iterable or dataframe and returning the results as a dataframe. You only need to implement `lookup_ips` in your class if the service has some kind of native ability to handle a batch of IPs (IpStack has this).

There are a couple of problems:
1. Looking at the code I can see that it is in need of refactoring...this is pretty old code and we (I) made some klunky mistakes and assumptions.
2. In several places we make a hard-coded call to GeoLiteLookup (e.g. in the Folium module and in Pivot functions). we really need to make this user configurable.
3. There is no easy way of using your own GeoIP provider with msticpy without checking it into the code.

Another thought here is that, if your geoip sources are simple http lookup APIs we could use the new (very new, not yet released) context providers for this - this would make the code even simpler.

Here is the sample GeoIP provider. If you are using geolocation services that are available to others and therefore make sense to have in msticpy, I'm all for that. Otherwise I'm happy to work with you to try to implement a simpler way of having replaceable providers - like a plugin model where you just include some config that tells msticpy where your geoip implementation is and it will just load and use it.

Apologies for the long answer but it isn't completely straightforward. We could consider converting this to a discussion. It might be useful to have in a more permanent place than an issue.

```python
from typing import Any, Iterable, List, Optional, Tuple
import httpx

from msticpy.context.geoip import GeoIpLookup
from msticpy.datamodel.entities import IpAddress, GeoLocation


class MyGeoLookup(GeoIpLookup):

    _GEO_URL = "https://mygeolookup.com/?key={api_key}&ip={ip_addr}"

    def __init__(self, api_key: Optional[str] = None):
        self._api_key = api_key
        super().__init__()

    def lookup_ip(
        self,
        ip_address: Optional[str] = None,
        ip_addr_list: Optional[Iterable] = None,
        ip_entity: Optional[IpAddress] = None,
    ) -> Tuple[List[Any], List[IpAddress]]:
        """
        Lookup IP location from IPStack web service.

        Parameters
        ----------
        ip_address : str, optional
            a single address to look up (the default is None)
        ip_addr_list : Iterable, optional
            a collection of addresses to lookup (the default is None)
        ip_entity : IpAddress, optional
            an IpAddress entity (the default is None) - any existing
            data in the Location property will be overwritten

        Returns
        -------
        Tuple[List[Any], List[IpAddress]]:
            raw geolocation results and same results as IpAddress entities with
            populated Location property.

        Raises
        ------
        ConnectionError
            Invalid status returned from http request
        PermissionError
            Service refused request (e.g. requesting batch of addresses
            on free tier API key)

        """
        ip_list = self._ip_params_to_list(ip_address, ip_addr_list, ip_entity)
        output_raw = []
        output_entities = []
        for ip_addr in ip_list:
            resp = httpx.get(self._GEO_URL.format(
                api_key=self._api_key,
                ip_addr=ip_addr
            ))
            if resp.status == 200:
                output_entities.append(self._create_ip_entity(resp.json(), ip_entity))
            output_raw.append((resp.json(), resp.status))
        return output_raw, output_entities

    # example from IPStack - obviously need to map the correct
    # properties from the response.    
    @staticmethod
    def _create_ip_entity(ip_loc: dict, ip_entity) -> IpAddress:
        if not ip_entity:
            ip_entity = IpAddress()
            ip_entity.Address = ip_loc["ip"]
        geo_entity = GeoLocation()
        geo_entity.CountryCode = ip_loc["country_code"]

        geo_entity.CountryName = ip_loc["country_name"]
        geo_entity.State = ip_loc["region_name"]
        geo_entity.City = ip_loc["city"]
        geo_entity.Longitude = ip_loc["longitude"]
        geo_entity.Latitude = ip_loc["latitude"]
        if "connection" in ip_loc:
            geo_entity.Asn = ip_loc["connection"]["asn"]
        ip_entity.Location = geo_entity
        return ip_entity
```

**Comment by mathurin68** [comment]
Hey @ianhelle!  Thank you for this answer, I have access to a couple through my agency, I'm not sure it's worth the trouble to put them in????  However, if there's some way I can be a "tester" for something you want to try let me know!!
